bootstrap: Report errors on standard error
Signed-off-by: Mintsuki <mintsuki@protonmail.com>

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -87,8 +87,8 @@ for auxfile in $AUXFILES; do
     if ! test -f build-aux/$auxfile; then
         if ! $AUTOMAKE --print-libdir >/dev/null 2>&1; then
             set +x
-            echo "error: Broken autoreconf detected, but missing or broken automake."
-            echo "       Please make sure automake is installed and working."
+            echo "error: Broken autoreconf detected, but missing or broken automake." 1>&2
+            echo "       Please make sure automake is installed and working." 1>&2
             exit 1
         fi
         AUTOMAKE_LIBDIR="$($AUTOMAKE --print-libdir)"
